import type { RouteTypesManifest } from './route-types-shared'

// TODO: add support for processing redirects and rewrites
// see old next-types-plugin source code for reference
// TODO: make sure we're using isDynamicRoute where appropriate

function generateRouteTypes(routesManifest: RouteTypesManifest): string {
  const appRoutes = Object.keys(routesManifest.appRoutes).sort()
  const pageRoutes = Object.keys(routesManifest.pageRoutes).sort()
  const layoutRoutes = Object.keys(routesManifest.layoutRoutes).sort()

  let result = ''

  // Generate AppRoutes union type
  if (appRoutes.length > 0) {
    result += `type AppRoutes = ${appRoutes.map((route) => `"${route}"`).join(' | ')}\n`
  } else {
    result += 'type AppRoutes = never\n'
  }

  // Generate PageRoutes union type
  if (pageRoutes.length > 0) {
    result += `type PageRoutes = ${pageRoutes.map((route) => `"${route}"`).join(' | ')}\n`
  } else {
    result += 'type PageRoutes = never\n'
  }

  // Generate LayoutRoutes union type
  if (layoutRoutes.length > 0) {
    result += `type LayoutRoutes = ${layoutRoutes.map((route) => `"${route}"`).join(' | ')}\n`
  } else {
    result += 'type LayoutRoutes = never\n'
  }

  result += 'type Routes = AppRoutes | PageRoutes | LayoutRoutes\n'

  return result
}

function generateParamTypes(routesManifest: RouteTypesManifest): string {
  const allRoutes = {
    ...routesManifest.appRoutes,
    ...routesManifest.pageRoutes,
    ...routesManifest.layoutRoutes,
  }

  let paramTypes = 'type ParamMap = {\n'

  // Sort routes deterministically for consistent output
  const sortedRoutes = Object.entries(allRoutes).sort(([a], [b]) =>
    a.localeCompare(b)
  )

  for (const [route, routeInfo] of sortedRoutes) {
    const { groups } = routeInfo
    let paramType = '{'

    // Process each group based on its properties
    for (const [key, group] of Object.entries(groups)) {
      if (group.repeat) {
        // Catch-all parameters
        if (group.optional) {
          paramType += ` ${key}?: string[];`
        } else {
          paramType += ` ${key}: string[];`
        }
      } else {
        // Regular parameters
        if (group.optional) {
          paramType += ` ${key}?: string;`
        } else {
          paramType += ` ${key}: string;`
        }
      }
    }

    paramType += ' }'

    paramTypes += `  '${route}': ${paramType}\n`
  }

  paramTypes += '}\n'
  return paramTypes
}

function generateLayoutSlotMap(routesManifest: RouteTypesManifest): string {
  let slotMap = 'type LayoutSlotMap = {\n'

  // Sort routes deterministically for consistent output
  const sortedLayoutRoutes = Object.entries(routesManifest.layoutRoutes).sort(
    ([a], [b]) => a.localeCompare(b)
  )

  for (const [route, routeInfo] of sortedLayoutRoutes) {
    if ('slots' in routeInfo) {
      const slots = routeInfo.slots.sort()
      if (slots.length > 0) {
        slotMap += `  '${route}': ${slots.map((slot) => `"${slot}"`).join(' | ')}\n`
      } else {
        slotMap += `  '${route}': never\n`
      }
    } else {
      slotMap += `  '${route}': never\n`
    }
  }

  slotMap += '}\n'
  return slotMap
}

export function generateRouteTypesFile(
  routesManifest: RouteTypesManifest
): string {
  const routeTypes = generateRouteTypes(routesManifest)
  const paramTypes = generateParamTypes(routesManifest)
  const layoutSlotMap = generateLayoutSlotMap(routesManifest)

  return `// This file is generated automatically by Next.js
// Do not edit this file manually

${routeTypes}

${paramTypes}

export type ParamsOf<P extends Routes> = ParamMap[P]

${layoutSlotMap}

type LayoutChildren<P extends LayoutRoutes> = { children: React.ReactNode } & {
  [K in LayoutSlotMap[P]]: React.ReactNode
}

export type { AppRoutes, PageRoutes, LayoutRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * \`\`\`tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * \`\`\`
   */
  type PageProps<P extends AppRoutes> = {
    params: Promise<ParamsOf<P>>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }
  
  /**
   * Props for Next.js App Router layout components
   * @example
   * \`\`\`tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * \`\`\`
   */
  type LayoutProps<P extends LayoutRoutes> = {
    params: Promise<ParamsOf<P>>
  } & LayoutChildren<P>
}

// Module augmentations for typed links
declare module 'next/link' {
  import type { LinkProps as OriginalLinkProps } from 'next/dist/client/app-dir/link.js'
  import type { AnchorHTMLAttributes, DetailedHTMLProps } from 'react'
  import type { UrlObject } from 'url'

  type LinkRestProps = Omit<
    Omit<
      DetailedHTMLProps<
        AnchorHTMLAttributes<HTMLAnchorElement>,
        HTMLAnchorElement
      >,
      keyof OriginalLinkProps
    > &
      OriginalLinkProps,
    'href' | 'path' | 'params' | 'searchParams'
  >

  type LinkPropsWithHref = LinkRestProps & {
    /**
     * The path or URL to navigate to. It can also be an object.
     * Accepts any string for external URLs and backwards compatibility.
     * 
     * @example
     * \`\`\`tsx
     * <Link href="/about">About</Link>
     * <Link href="https://example.com">External</Link>
     * <Link href={{ pathname: "/about", query: { tab: "contact" } }}>About</Link>
     * \`\`\`
     */
    href: string | UrlObject
    path?: never
    params?: never
    searchParams?: never
  }

  type LinkPropsWithPath<T extends Routes> = LinkRestProps & {
    href?: never
    /**
     * The route path template for typed navigation
     * 
     * @example
     * \`\`\`tsx
     * <Link path="/blog/[slug]" params={{ slug: "my-post" }}>My Post</Link>
     * \`\`\`
     */
    path: T
    /**
     * Parameters for dynamic route segments. Required if the route has dynamic segments.
     * 
     * @example
     * \`\`\`tsx
     * // For route /blog/[slug]
     * <Link path="/blog/[slug]" params={{ slug: "hello-world" }}>Post</Link>
     * 
     * // For route /docs/[...slug]  
     * <Link path="/docs/[...slug]" params={{ slug: ["api", "reference"] }}>Docs</Link>
     * \`\`\`
     */
    params: {} extends ParamsOf<T> ? {} : ParamsOf<T>
    /**
     * Search parameters to append to the URL as query string
     * 
     * @example
     * \`\`\`tsx
     * <Link path="/search" searchParams={{ q: "react", filter: "latest" }}>
     *   Search React
     * </Link>
     * \`\`\`
     */
    searchParams?: Record<string, string | string[]>
  }

  export type LinkProps<RouteInferType extends Routes = Routes> = 
    | LinkPropsWithHref
    | LinkPropsWithPath<RouteInferType>

  /**
   * A React component that extends the HTML \`<a>\` element to provide
   * prefetching and client-side navigation. This is the primary way to navigate between routes in Next.js.
   *
   * @example
   * \`\`\`tsx
   * // Traditional href usage (accepts any string)
   * <Link href="/about">About</Link>
   * <Link href="https://example.com">External</Link>
   *
   * // Typed path usage with parameters
   * <Link path="/blog/[slug]" params={{ slug: "my-post" }}>
   *   My Blog Post
   * </Link>
   *
   * // With search parameters
   * <Link path="/search" searchParams={{ q: "nextjs" }}>
   *   Search NextJS
   * </Link>
   * \`\`\`
   */
  export default function Link<RouteType extends Routes = Routes>(
    props: LinkProps<RouteType> & { children: React.ReactNode }
  ): JSX.Element
}

declare module 'next/navigation' {
  export * from 'next/dist/client/components/navigation.js'

  import type { NavigateOptions, AppRouterInstance as OriginalAppRouterInstance } from 'next/dist/shared/lib/app-router-context.shared-runtime.js'
  
  interface AppRouterInstance extends OriginalAppRouterInstance {
    /**
     * Navigate to the provided href.
     * Pushes a new history entry.
     */
    push<RouteType extends Routes>(href: RouteType, options?: NavigateOptions): void
    /**
     * Navigate to the provided href.
     * Replaces the current history entry.
     */
    replace<RouteType extends Routes>(href: RouteType, options?: NavigateOptions): void
    /**
     * Prefetch the provided href.
     */
    prefetch<RouteType extends Routes>(href: RouteType): void
  }

  export function useRouter(): AppRouterInstance;
}
`
}
